export { iPhoneExecutor } from './executor.js';
export { SessionManager, sessionManager } from './session.js';
export { selectDevice, discoverDevices, getDeviceInfo, verifyDeviceReady } from './device.js';
export { resolveAppNameToBundleId } from './apps.js';
export { verifyWDA, buildWDA, installWDA, launchWDA, type WDAStatus } from './wda.js';
export { iPhoneAgentError, DeviceSelectionError, WDAVerificationError } from './errors.js';
export { AppiumDriver } from '@athena-os/driver';
export type { Driver } from '@athena-os/driver';
export type * from '@athena-os/core';
export type { Executor } from '@athena-os/executor';
