export {
  AthenaError,
  DeviceError,
  DeviceNotConnectedError,
  DeviceNotFoundError,
  DeviceNotReadyError,
  SessionError,
  SessionExpiredError,
  ElementNotFoundError,
  ActionError,
  AppLaunchError,
  ActionExecutionError,
  TimeoutError,
  ConfigurationError,
  ValidationError,
  InternalError,
  DriverError,
  WebDriverAgentError,
  isAthenaError,
  toAthenaError,
} from '@athena-os/core';
